export const MODULE_IDS = {
  DASHBOARD: 5,
  NATIONAL_TEAMS: 6,
  FEDERATIONS: 7,
  SPORTS_PROFESSIONALS: 8,
  TRAININGS: 9,
  ISONGA_PROGRAMS: 10,
  ACADEMIES: 11,
  INFRASTRUCTURE: 12,
  SPORTS_TOURISM: 13,
  DOCUMENTS: 14,
  CONTRACTS: 15,
  APPOINTMENTS: 16,
  EMPLOYEE: 17,
  USERS: 18,
  SPORTS_FOR_ALL: 19
};

export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete'
}; 